proxy-providers:
  Airport_01:
    type: http
    interval: 1800
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
    proxy: "ğŸŸ¢ ç›´è¿"
    url: "https://hongxingdl.love/hxyunvip?token=de21eda356ac17b973a1780f1466d708"

global-ua: clash

port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
ipv6: false
allow-lan: true
unified-delay: true
tcp-concurrent: true
authentication:
  - "clash:SoxMoox"

geodata-mode: false
geodata-loader: standard
geo-auto-update: true
geo-update-interval: 48
geo-url:
  geosite: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/downlond/latest/geosite.dat"
  mmdb: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/downlond/latest/geoip-lite.metadb"
  geoip: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/downlond/latest/geoip-lite.dat"
  asn: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/downlond/latest/GeoLite2-ASN.mmdb"

external-controller: 0.0.0.0:9090
secret: "SoxMoox0513."
external-ui: "/usr/share/openclash/ui"
external-ui-name: zashboard
external-ui-url: "https://github.com/Zephyruso/zashboard/archive/refs/heads/gh-pages.zip"

find-process-mode: strict
global-client-fingerprint: chrome
keep-alive-idle: 600
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: true
  override-destination: true
  sniff:
    QUIC:
      ports:
      - 443
    TLS:
      ports:
      - 443
      - 8443
    HTTP:
      ports:
      - 80
      - 8080-8880
      override-destination: true
  force-domain:
  - "+.netflix.com"
  - "+.nflxvideo.net"
  - "+.amazonaws.com"
  - "+.media.dssott.com"
  skip-domain:
  - "+.apple.com"
  - "Mijia Cloud"
  - "dlg.io.mi.com"
  - "+.oray.com"
  - "+.sunlogin.net"
  - "+.push.apple.com"
  parse-pure-ip: true

tun:
  enable: true
  stack: mixed
  device: utun
  dns-hijack:
  - 127.0.0.1:53
  endpoint-independent-nat: true
  auto-route: false
  auto-detect-interface: false
  auto-redirect: false
  strict-route: false

dns:
  enable: true
  listen: 0.0.0.0:7874
  ipv6: false
  respect-rules: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
  - "rule-set:private_domain,cn_domain"
  - "+.services.googleapis.cn"
  - "+.xn--ngstr-lra8j.com"
  - "time.*.com"
  - "+.pool.ntp.org"
  - "+.ntp.tencent.com"
  - "+.ntp1.aliyun.com"
  - "+.ntp.ntsc.ac.cn"
  - "+.cn.ntp.org.cn"
  - "*.lan"
  - "*.localdomain"
  - "*.example"
  - "*.invalid"
  - "*.localhost"
  - "*.test"
  - "*.local"
  - "*.home.arpa"
  - "time.*.gov"
  - "time.*.edu.cn"
  - "time.*.apple.com"
  - "time-ios.apple.com"
  - "time1.*.com"
  - "time2.*.com"
  - "time3.*.com"
  - "time4.*.com"
  - "time5.*.com"
  - "time6.*.com"
  - "time7.*.com"
  - "ntp.*.com"
  - "ntp1.*.com"
  - "ntp2.*.com"
  - "ntp3.*.com"
  - "ntp4.*.com"
  - "ntp5.*.com"
  - "ntp6.*.com"
  - "ntp7.*.com"
  - "*.time.edu.cn"
  - "*.ntp.org.cn"
  - "time1.cloud.tencent.com"
  - "music.163.com"
  - "*.music.163.com"
  - "*.126.net"
  - "musicapi.taihe.com"
  - "music.taihe.com"
  - "songsearch.kugou.com"
  - "trackercdn.kugou.com"
  - "*.kuwo.cn"
  - "api-jooxtt.sanook.com"
  - "api.joox.com"
  - "joox.com"
  - "y.qq.com"
  - "*.y.qq.com"
  - "streamoc.music.tc.qq.com"
  - "mobileoc.music.tc.qq.com"
  - "isure.stream.qqmusic.qq.com"
  - "l.stream.qqmusic.qq.com"
  - "aqqmusic.tc.qq.com"
  - "amobile.music.tc.qq.com"
  - "*.xiami.com"
  - "*.music.migu.cn"
  - "music.migu.cn"
  - "+.msftconnecttest.com"
  - "+.msftncsi.com"
  - "localhost.ptlogin2.qq.com"
  - "localhost.sec.qq.com"
  - "+.qq.com"
  - "+.tencent.com"
  - "+.srv.nintendo.net"
  - "*.n.n.srv.nintendo.net"
  - "+.cdn.nintendo.net"
  - "+.stun.playstation.net"
  - "xbox.*.*.microsoft.com"
  - "*.*.xboxlive.com"
  - "xbox.*.microsoft.com"
  - "xnotify.xboxlive.com"
  - "+.battlenet.com.cn"
  - "+.wotgame.cn"
  - "+.wggames.cn"
  - "+.wowsgame.cn"
  - "+.wargaming.net"
  - "proxy.golang.org"
  - "stun.*.*"
  - "stun.*.*.*"
  - "+.stun.*.*"
  - "+.stun.*.*.*"
  - "+.stun.*.*.*.*"
  - "+.stun.*.*.*.*.*"
  - "heartbeat.belkin.com"
  - "*.linksys.com"
  - "*.linksyssmartwifi.com"
  - "*.router.asus.com"
  - "mesu.apple.com"
  - "swscan.apple.com"
  - "swquery.apple.com"
  - "swdownload.apple.com"
  - "swcdn.apple.com"
  - "swdist.apple.com"
  - "lens.l.google.com"
  - "stun.l.google.com"
  - "na.b.g-tun.com"
  - "+.nflxvideo.net"
  - "*.square-enix.com"
  - "*.finalfantasyxiv.com"
  - "*.ffxiv.com"
  - "*.ff14.sdo.com"
  - "ff.dorado.sdo.com"
  - "*.mcdn.bilivideo.cn"
  - "+.media.dssott.com"
  - "shark007.net"
  - "Mijia Cloud"
  - "+.cmbchina.com"
  - "+.cmbimg.com"
  - "local.adguard.org"
  - "+.sandai.net"
  - "+.n0808.com"
  - "+.uu.163.com"
  - "ps.res.netease.com"
  - "+.pub.3gppnetwork.org"
  - "geosite:category-games"
  default-nameserver:
  - 10.0.0.1
  - 223.5.5.5
  - 119.29.29.29
  - 114.114.114.114
  proxy-server-nameserver:
  - 10.0.0.1
  - 223.5.5.5
  - 119.29.29.29
  nameserver:
  - 10.0.0.1
  - 202.99.224.67
  - 202.99.224.68
nameserver-policy:
  rule-set:private_domin,cn_domain:
  - 10.0.0.1
  - 223.5.5.5
  - 119.29.29.29
  rule-set:geolocation-!cn:
  - "https://dns.cloudflare.com/dns-query"
  - "https://dns.google/dns-query"

proxies:
- name: "ğŸŸ¢ ç›´è¿"
  type: direct
  udp: true

pr:
  type: select
  proxies: &1
  - "ğŸª„ èŠ‚ç‚¹é€‰æ‹©"
  - "â™¾ï¸ é¦™æ¸¯æ•…è½¬"
  - "â™¾ï¸ æ—¥æœ¬æ•…è½¬"
  - "â™¾ï¸ ç¾å›½æ•…è½¬"
  - "â™»ï¸ è‡ªåŠ¨é€‰æ‹©"
  - "â™»ï¸ é¦™æ¸¯è‡ªåŠ¨"
  - "â™»ï¸ å°æ¹¾è‡ªåŠ¨"
  - "â™»ï¸ æ—¥æœ¬è‡ªåŠ¨"
  - "â™»ï¸ éŸ©å›½è‡ªåŠ¨"
  - "â™»ï¸ æ–°åŠ å¡è‡ªåŠ¨"
  - "â™»ï¸ ç¾å›½è‡ªåŠ¨"
  - "â™»ï¸ IPV6è‡ªåŠ¨"
  - "ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹"
  - "ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹"
  - "ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹"
  - "ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹"
  - "ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹"
  - "ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹"
  - "ğŸ‡¨ğŸ‡¦ åŠ æ‹¿å¤§èŠ‚ç‚¹"
  - "ğŸ‘» IPV6èŠ‚ç‚¹"
  - "ğŸŒ å…¨éƒ¨èŠ‚ç‚¹"
  - "ğŸŸ¢ ç›´è¿"
proxy-groups:
- name: "ğŸª„ èŠ‚ç‚¹é€‰æ‹©"
  type: select
  proxies:
  - "â™¾ï¸ é¦™æ¸¯æ•…è½¬"
  - "â™¾ï¸ æ—¥æœ¬æ•…è½¬"
  - "â™¾ï¸ ç¾å›½æ•…è½¬"
  - "â™»ï¸ è‡ªåŠ¨é€‰æ‹©"
  - "â™»ï¸ é¦™æ¸¯è‡ªåŠ¨"
  - "â™»ï¸ å°æ¹¾è‡ªåŠ¨"
  - "â™»ï¸ æ—¥æœ¬è‡ªåŠ¨"
  - "â™»ï¸ éŸ©å›½è‡ªåŠ¨"
  - "â™»ï¸ æ–°åŠ å¡è‡ªåŠ¨"
  - "â™»ï¸ ç¾å›½è‡ªåŠ¨"
  - "â™»ï¸ IPV6è‡ªåŠ¨"
  - "ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹"
  - "ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹"
  - "ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹"
  - "ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹"
  - "ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹"
  - "ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹"
  - "ğŸ‡¨ğŸ‡¦ åŠ æ‹¿å¤§èŠ‚ç‚¹"
  - "ğŸ‘» IPV6èŠ‚ç‚¹"
  - "ğŸŒ å…¨éƒ¨èŠ‚ç‚¹"
  - "ğŸŸ¢ ç›´è¿"
- name: "ğŸ“¹ YouTube"
  type: select
  proxies: *1
- name: "ğŸª GoogleFCM"
  type: select
  proxies: *1
- name: "ğŸ‘‘ Google"
  type: select
  proxies: *1
- name: "âœ¨ï¸ ChatGPT"
  type: select
  proxies: *1
- name: "ğŸ‰ Gemini"
  type: select
  proxies: *1
- name: "ğŸ©» GitHub"
  type: select
  proxies: *1
- name: "ğŸŒ¸ Pixiv"
  type: select
  proxies: *1
- name: "ğŸ’½ OneDrive"
  type: select
  proxies: *1
- name: "ğŸ–¥ï¸ï¸ Microsoft"
  type: select
  proxies: *1
- name: "ğŸ“± TikTok"
  type: select
  proxies: *1
- name: "ğŸ“ Whatsapp"
  type: select
  proxies: *1
- name: "âšœï¸ Instagram"
  type: select
  proxies: *1
- name: "ğŸ“” Facebook"
  type: select
  proxies: *1
- name: "âŒï¸ Twitter"
  type: select
  proxies: *1
- name: "ğŸ“  Telegram"
  type: select
  proxies: *1
- name: "ğŸ“½ï¸ NETFLIX"
  type: select
  proxies: *1
- name: "âœˆï¸ Speedtest"
  type: select
  proxies: *1
- name: "ğŸ’³ï¸ï¸ PayPal"
  type: select
  proxies: *1
- name: "ğŸ Apple"
  type: select
  proxies:
  - "ğŸŸ¢ ç›´è¿"
  - "ğŸª„ èŠ‚ç‚¹é€‰æ‹©"
- name: "ğŸ›°ï¸ï¸ å…¨çƒç›´è¿"
  type: select
  proxies:
  - "ğŸŸ¢ ç›´è¿"
  - "ğŸª„ èŠ‚ç‚¹é€‰æ‹©"
- name: "ğŸ æ¼ç½‘ä¹‹é±¼"
  type: select
  proxies: *1
- name: "ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹"
  type: select
  include-all: true
  filter: "(?i)æ¸¯|hk|hongkong|hong kong"
- name: "ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹"
  type: select
  include-all: true
  filter: "(?i)å°|tw|taiwan"
- name: "ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹"
  type: select
  include-all: true
  filter: "(?i)æ—¥æœ¬|jp|japan"
- name: "ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹"
  type: select
  include-all: true
  filter: "(?i)ç¾|us|unitedstates|united states"
- name: "ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹"
  type: select
  include-all: true
  filter: "(?i)æ–°åŠ å¡|sg|singapore"
- name: "ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹"
  type: select
  include-all: true
  filter: "(?i)éŸ©å›½|kr|korea"
- name: "ğŸ‡¨ğŸ‡¦ åŠ æ‹¿å¤§èŠ‚ç‚¹"
  type: select
  include-all: true
  filter: "(?=.*(åŠ |ca|canada))^((?!(å°|æ—¥|éŸ©|æ·±|æ–°|ç¾|)).)*$"
- name: "ğŸ‘» IPV6èŠ‚ç‚¹"
  type: select
  include-all: true
  filter: "(?i)IPV6|ipv6"
- name: "â™¾ï¸ é¦™æ¸¯æ•…è½¬"
  type: fallback
  include-all: true
  tolerance: 20
  interval: 180
  filter: "(?=.*(æ¸¯|HK|(?i)Hongkong|Hong kong))^((?!(å°|æ—¥|éŸ©|æ–°|æ·±|ç¾)).)*$"
- name: "â™¾ï¸ å°æ¹¾æ•…è½¬"
  type: fallback
  include-all: true
  tolerance: 20
  interval: 180
  filter: "(?=.*(å°|TW|(?i)Taiwan))^((?!(æ¸¯|æ—¥|éŸ©|æ–°|æ·±|ç¾)).)*$"
- name: "â™¾ï¸ ç¾å›½æ•…è½¬"
  type: fallback
  include-all: true
  tolerance: 20
  interval: 180
  filter: "(?=.*(ç¾|US|(?i)States|America))^((?!(æ¸¯|å°|æ—¥|éŸ©|æ–°)).)*$"
- name: "â™¾ï¸ æ—¥æœ¬æ•…è½¬"
  type: fallback
  include-all: true
  tolerance: 20
  interval: 180
  filter: "(?=.*(æ—¥|JP|(?i)Japan))^((?!(æ¸¯|å°|éŸ©|æ–°|ç¾|å°¼)).)*$"
- name: "â™»ï¸ è‡ªåŠ¨é€‰æ‹©"
  type: url-test
  include-all: true
  tolerance: 100
  interval: 180
  filter: "^((?!(ç›´è¿|å®˜ç½‘|å‰©ä½™|åˆ°æœŸ|å¼‚å¸¸|å¤±è´¥)).)*$"
- name: "â™»ï¸ é¦™æ¸¯è‡ªåŠ¨"
  type: url-test
  include-all: true
  tolerance: 100
  interval: 180
  filter: "(?=.*(æ¸¯|HK|(?i)Hongkong|Hong kong))^((?!(å°|æ—¥|éŸ©|æ–°|æ·±|ç¾)).)*$"
- name: "â™»ï¸ å°æ¹¾è‡ªåŠ¨"
  type: url-test
  include-all: true
  tolerance: 100
  interval: 180
  filter: "(?=.*(å°|TW|(?i)Taiwan))^((?!(æ¸¯|æ—¥|éŸ©|æ–°|æ·±|ç¾)).)*$"
- name: "â™»ï¸ æ—¥æœ¬è‡ªåŠ¨"
  type: url-test
  include-all: true
  tolerance: 100
  interval: 180
  filter: "(?=.*(æ—¥|JP|(?i)Japan))^((?!(æ¸¯|å°|éŸ©|æ–°|ç¾|å°¼)).)*$"
- name: "â™»ï¸ ç¾å›½è‡ªåŠ¨"
  type: url-test
  include-all: true
  tolerance: 100
  interval: 180
  filter: "(?=.*(ç¾|US|(?i)States|America))^((?!(æ¸¯|å°|æ—¥|éŸ©|æ–°)).)*$"
- name: "â™»ï¸ éŸ©å›½è‡ªåŠ¨"
  type: url-test
  include-all: true
  tolerance: 100
  interval: 180
  filter: "(?=.*(éŸ©|KR|(?i)Korea))^((?!(å°|æ—¥|æ–°|æ·±|ç¾)).)*$"
- name: "â™»ï¸ æ–°åŠ å¡è‡ªåŠ¨"
  type: url-test
  include-all: true
  tolerance: 100
  interval: 180
  filter: "(?=.*((?i)æ–°åŠ å¡|Sg|singapore))^((?!(å°|æ—¥|éŸ©|æ·±|ç¾)).)*$"
- name: "â™»ï¸ IPV6è‡ªåŠ¨"
  type: select
  include-all: true
  tolerance: 20
  interval: 300
  filter: "(?i)IPV6|ipv6"
- name: "ğŸŒ å…¨éƒ¨èŠ‚ç‚¹"
  type: select
  include-all: true
  filter: "^((?!(ç›´è¿|å®˜ç½‘|å‰©ä½™|åˆ°æœŸ|å¼‚å¸¸|å¤±è´¥)).)*$"
rules:
- "RULE-SET,private_domain,ğŸŸ¢ ç›´è¿"
- "RULE-SET,direct,ğŸŸ¢ ç›´è¿"
- "RULE-SET,apple_domain,ğŸ Apple"
- "RULE-SET,proxy,ğŸª„ èŠ‚ç‚¹é€‰æ‹©"
- "RULE-SET,ai,âœ¨ï¸ ChatGPT"
- "RULE-SET,gemini_domain,ğŸ‰ Gemini"
- "RULE-SET,github_domain,ğŸ©» GitHub"
- "RULE-SET,pixiv_domain,ğŸŒ¸ Pixiv"
- "RULE-SET,youtube_domain,ğŸ“¹ YouTube"
- "RULE-SET,googlefcm_domain,ğŸª GoogleFCM"
- "RULE-SET,google_domain,ğŸ‘‘ Google"
- "RULE-SET,onedrive_domain,ğŸ’½ OneDrive"
- "RULE-SET,microsoft_domain,ğŸ–¥ï¸ï¸ Microsoft"
- "RULE-SET,tiktok_domain,ğŸ“± TikTok"
- "RULE-SET,speedtest_domain,âœˆï¸ Speedtest"
- "RULE-SET,whatsapp_domain,ğŸ“ Whatsapp"
- "RULE-SET,instagram_domain,âšœï¸ Instagram"
- "RULE-SET,facebook_domain,ğŸ“” Facebook"
- "RULE-SET,twitter_domain,âŒï¸ Twitter"
- "RULE-SET,telegram_domain,ğŸ“  Telegram"
- "RULE-SET,netflix_domain,ğŸ“½ï¸ NETFLIX"
- "RULE-SET,paypal_domain,ğŸ’³ï¸ï¸ PayPal"
- "RULE-SET,geolocation-!cn,ğŸª„ èŠ‚ç‚¹é€‰æ‹©"
- "RULE-SET,cn_domain,ğŸ›°ï¸ï¸ å…¨çƒç›´è¿"
- "RULE-SET,google_ip,ğŸ‘‘ Google,no-resolve"
- "RULE-SET,netflix_ip,ğŸ“½ï¸ NETFLIX,no-resolve"
- "RULE-SET,whatsapp_ip,ğŸ“ Whatsapp,no-resolve"
- "RULE-SET,instagram_ip,âšœï¸ Instagram,no-resolve"
- "RULE-SET,facebook.ip,ğŸ“” Facebook,no-resolve"
- "RULE-SET,twitter_ip,âŒï¸ Twitter,no-resolve"
- "RULE-SET,telegram_ip,ğŸ“  Telegram,no-resolve"
- "RULE-SET,cn_ip,ğŸ›°ï¸ï¸ å…¨çƒç›´è¿"
- "MATCH,ğŸ æ¼ç½‘ä¹‹é±¼"
rule-anchor:
  ip:
    type: http
    interval: 86400
    behavior: ipcidr
    format: mrs
  domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
  soxmoox:
    type: http
    interval: 86400
    behavior: domain
    format: text
  class:
    type: http
    interval: 86400
    behavior: classical
    format: text
rule-providers:
  private_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs
  direct:
    type: http
    interval: 86400
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/SoxMoox/Open-clash/refs/heads/main/Direct.list
  proxy:
    type: http
    interval: 86400
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/SoxMoox/Open-clash/refs/heads/main/ProxyLite.list
  ai:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-ai-chat-!cn.mrs
  gemini_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/gemini.mrs
  youtube_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs
  googlefcm_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/googlefcm.mrs
  google_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs
  github_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.mrs
  pixiv_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/pixiv.mrs
  whatsapp_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/whatsapp.mrs
  instagram_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/instagram.mrs
  facebook_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/facebook.mrs
  twitter_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/x.mrs
  telegram_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs
  netflix_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.mrs
  paypal_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/paypal.mrs
  onedrive_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/onedrive.mrs
  microsoft_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.mrs
  apple_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple-cn.mrs
  speedtest_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/ookla-speedtest.mrs
  tiktok_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tiktok.mrs
  gfw_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/gfw.mrs
  geolocation-!cn:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs
  cn_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs
  cn_ip:
    type: http
    interval: 86400
    behavior: ipcidr
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs
  google_ip:
    type: http
    interval: 86400
    behavior: ipcidr
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.mrs
  gemini_ip:
    type: http
    interval: 86400
    behavior: ipcidr
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/gemini.mrs
  whatsapp_ip:
    type: http
    interval: 86400
    behavior: ipcidr
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/whatsapp.mrs
  instagram_ip:
    type: http
    interval: 86400
    behavior: ipcidr
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.mrs
  facebook.ip:
    type: http
    interval: 86400
    behavior: ipcidr
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/facebook.mrs
  twitter_ip:
    type: http
    interval: 86400
    behavior: ipcidr
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/x.mrs
  telegram_ip:
    type: http
    interval: 86400
    behavior: ipcidr
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.mrs
  netflix_ip:
    type: http
    interval: 86400
    behavior: ipcidr
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.mrs
mode: rule
bind-address: "*"
